"""
cad — parametric CAD solids via CadQuery (Report #1 / CadQuery-optional).

User-facing promise: "diagrams/CAD-like creation". JARVIS now speaks
real CAD: a short CadQuery snippet → STL + STEP + SVG preview written
to <base>/cad/.

Dependencies (both FREE, guarded — never faked):
  * CadQuery (Apache-2.0) — `pip install cadquery`
  * runs the snippet in a SUBPROCESS exactly like code_helper runs
    code (isolation, timeout, captured stderr → honest error report)

WHY NOT A DUPLICATE: diagram.py draws 2D svg from a text spec; chart.py
plots data. This exports manufacturable 3D geometry (STL/STEP).
"""
from __future__ import annotations

import importlib.util
import subprocess
import sys
import time
from pathlib import Path

_INSTALL = ("CadQuery not installed — free (Apache-2.0): "
            "`pip install cadquery` (~80 MB, needs conda/pip wheel). "
            "I export real STL/STEP geometry only — no placeholder "
            "files when the library is missing.")
_TIMEOUT = 120


# ── seams (tests replace these) ────────────────────────────────────────────

def _has_cq() -> bool:
    return importlib.util.find_spec("cadquery") is not None


def _base_dir() -> Path:
    from config import get_base_dir
    return get_base_dir()


def _run_script(script_path: Path, timeout: int = _TIMEOUT) -> str:
    """Run the generated CadQuery script in an isolated interpreter.
    Returns combined output; raises on non-zero exit."""
    proc = subprocess.run(
        [sys.executable, str(script_path)],
        capture_output=True, text=True, timeout=timeout,
        cwd=str(script_path.parent))
    if proc.returncode != 0:
        tail = ((proc.stderr or "") + (proc.stdout or ""))[-600:]
        raise RuntimeError(f"script failed (exit {proc.returncode}):\n{tail}")
    return (proc.stdout or "") + (proc.stderr or "")


def _build_script(code: str, stl: Path, step: Path, svg: Path) -> str:
    """Wrap the user's snippet with the export tail (pure — tested)."""
    body = code.rstrip()
    if "```" in body:                       # tolerate pasted fences
        lines = [l for l in body.splitlines()
                 if not l.strip().startswith("```")]
        body = "\n".join(lines).strip()
    return (
        "# generated by JARVIS cad — CadQuery snippet runner\n"
        "import cadquery as cq\n\n"
        f"{body}\n\n"
        "# ---- JARVIS export tail ----\n"
        "if 'result' not in dir():\n"
        "    raise SystemExit('snippet must leave a `result` Workplane')\n"
        f"cq.exporters.export(result, r'{stl}')\n"
        f"try:\n    cq.exporters.export(result, r'{step}')\n"
        "except Exception:\n    pass\n"
        f"try:\n    cq.exporters.export(result, r'{svg}', "
        "opt={'projectionDir': (1, 1, 0.75), 'showAxes': False,\n"
        "         'strokeWidth': 0.2, 'showHidden': False})\n"
        "except Exception:\n    pass\n"
        "print('JARVIS_CAD_OK')\n"
    )


# ── tool ────────────────────────────────────────────────────────────────────

def cad(parameters: dict = None, player=None,
        session_memory=None) -> str:
    params = parameters or {}
    action = str(params.get("action", "build")).lower().strip()

    if action in ("status", "check"):
        if _has_cq():
            return "CadQuery available — cad code='result = cq.Workplane().box(10,10,10)'"
        return _INSTALL

    code = str(params.get("code", "") or params.get("snippet", "")).strip()
    if not code:
        return ("Give me a CadQuery snippet — cad code='result = "
                "cq.Workplane(\"XY\").box(20, 10, 5)' (the variable "
                "`result` gets exported to STL + STEP + SVG).")

    if not _has_cq():
        return _INSTALL

    out_dir = _base_dir() / "cad"
    out_dir.mkdir(parents=True, exist_ok=True)
    stamp = int(time.time())
    stl = out_dir / f"cad-{stamp}.stl"
    step = out_dir / f"cad-{stamp}.step"
    svg = out_dir / f"cad-{stamp}.svg"
    script = out_dir / f"cad-{stamp}.py"
    script.write_text(_build_script(code, stl, step, svg),
                      encoding="utf-8")

    try:
        _run_script(script)
    except subprocess.TimeoutExpired:
        return (f"CAD build timed out after {_TIMEOUT}s — snippet kept "
                f"at {script} (simplify the geometry and retry).")
    except RuntimeError as e:
        return (f"CAD build failed: {e}\nSnippet kept at {script} — "
                "fix it and re-run with the corrected code.")
    except Exception as e:
        return f"CAD build error: {e}"

    made = [p for p in (stl, step, svg) if p.is_file() and p.stat().st_size > 0]
    if not made:
        return (f"Script ran but produced no artifacts — snippet at "
                f"{script}. Did it export `result`?")
    if player is not None:
        try:
            player.show_content("CAD", "\n".join(
                f"{p.name} ({p.stat().st_size} B)" for p in made))
        except Exception:
            pass
    listing = ", ".join(f"{p.name} ({p.stat().st_size} B)" for p in made)
    return (f"CAD solid exported: {listing} — files in {out_dir}. "
            f"SVG preview opens in any browser; STL prints / STEP "
            f"imports into FreeCAD.")


TOOL = {
    "name": "cad",
    "description": (
        "Parametric 3D CAD: run a CadQuery snippet (variable `result` "
        "is exported) → STL + STEP + SVG preview in <base>/cad/. "
        "Use for any 'make a 3D model/enclosure/bracket/cad part' "
        "request. Requires free `pip install cadquery` — action=status "
        "checks; honest install line otherwise (no fake files)."),
    "parameters": {
        "type": "OBJECT",
        "properties": {
            "action": {"type": "STRING",
                       "description": "build (default) | status."},
            "code": {"type": "STRING",
                     "description": "CadQuery python ending with `result`. "
                                    "e.g. result = cq.Workplane().box(10,10,5)"},
        },
        "required": [],
    },
    "handler": cad,
}
